{% set name = "batch_jaro_winkler" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/n1tk/batch_jaro_winkler_new.git"

build:
  noarch: python
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - python >=3.6
    - cython >=0.20
    - setuptools
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - sysroot_linux-64 2.12 h77966d4_13
    #script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

  host:
    - numpy
    - pip
    - cython
    - python
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py37h9c2f6ca_1
    - expat 2.3.0 h9c3ff4c_0
    - gdbm 1.18 h0a1914f_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - pypy3.7 7.3.3 h7f93f3b_3
    - python 3.7.9 5_73_pypy
    - python_abi 3.7 1_pypy37_pp73
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py37h9c2f6ca_3
    - sqlite 3.35.3 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - pypy3.7 >=7.3.3
    - python >=3.7,<3.8.0a0
    - python_abi 3.7 *_pypy37_pp73
  
test:
  imports:
    - batch_jaro_winkler

about:
  home: "https://github.com/dbousque/batch_jaro_winkler"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Fast batch jaro winkler distance implementation in C99."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - n1tk
