{% set name = "batch_jaro_winkler" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/n1tk/batch_jaro_winkler_new.git"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  buid:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - setuptools
    - cython >=0.24.1
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - batch_jaro_winkler

about:
  home: "https://github.com/dbousque/batch_jaro_winkler"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Fast batch jaro winkler distance implementation in C99."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - n1tk
